# Generated by Django 5.1.2 on 2024-10-23 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_groups_remove_user_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('producer', 'Producer'), ('scriptwriter', 'Scriptwriter'), ('public', 'Public')], default='public', max_length=20),
        ),
    ]
