# Generated by Django 5.1.2 on 2024-10-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('script', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='total_dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='script',
            name='total_likes',
            field=models.IntegerField(default=0),
        ),
    ]
